name: Deploy Telegram Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ваш_сервер_ip
          username: ваш_username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/my-telegram-bot
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d